#!/usr/bin/env python

import rospy
from std_msgs.msg import String

if __name__ == '__main__':
    rospy.init_node("foopy_node")
    msg = String()
    msg.data = rospy.get_param("~message", "Hello, World!")
    pub = rospy.Publisher("~message", String, queue_size=1)
    r = rospy.Rate(1.5)

    while not rospy.is_shutdown():
        pub.publish(msg)
        r.sleep()
